resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: chemist/rsync-resource
    tag: latest

 
resources:
- name: input
  type: rsync-resource
  source:
    server: ci.internal
    base_dir: static
    static_identificator: input
    resource_type: r
- name: bin
  type: rsync-resource
  source:
    server: ci.internal
    base_dir: bin
    resource_type: rw
- name: output
  type: rsync-resource
  source:
    server: ci.internal
    base_dir: static
    resource_type: w
    static_identificator: output
  
      
jobs:
- name: test
  plan:
  - get: input
    trigger: false
  - task: bash script in task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: chemist/alpine-fpm, tag: "latest"}
      inputs:
      - name: input
      outputs:
      - name: bin
      run:
        path: bash
        args:
          - -exc
          - |
              ls -alhR .
              echo test > bin/test
              cp input/* bin/
  - put: bin
    params:
      identificator: check
      sync_dir: bin

- name: test1
  plan:
  - get: bin
    trigger: true
    passed: [test]
  - task: bash again
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: chemist/alpine-fpm, tag: "latest"}
      inputs:
      - name: bin
      outputs:
      - name: output
      run:
        path: bash
        args:
          - -exc
          - |
              ls -alhR .
              cp bin/* output/
  - put: output
    params:
      sync_dir: output
 
   
    

